import type { AccountRole } from '@/lib/auth/roles';
import type { InteractiveMessagePayload } from '@/lib/whatsapp/interactive';

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from '@/lib/whatsapp/interactive';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
  /**
   * The later of "last authenticated" (`profiles.last_sign_in_at`, 050)
   * and "last doing something" (`member_presence.last_seen_at`, 024).
   * Null for a member who has never opened the app — and null for
   * everybody when the caller is not an admin, because session times are
   * not roster information.
   */
  last_access_at?: string | null;
  /**
   * Per-person exceptions over the role (050). Empty for non-admins and
   * on a pre-050 database. Read through `@/lib/auth/capabilities`.
   */
  permission_overrides?: Partial<Record<string, boolean>>;
  /**
   * This member takes no automatic assignments (migration 051).
   * `undefined` on a pre-051 database, which reads as "in the rotation" —
   * the behaviour that database has.
   */
  auto_assign_opt_out?: boolean;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, 'owner'>;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  /**
   * Who last set `name` (migration 045). `'manual'` means a person typed it
   * and the inbound webhook must leave it alone — without this the WhatsApp
   * profile name overwrote every edit on the customer's next message.
   */
  name_source?: 'whatsapp' | 'manual';
  email?: string;
  company?: string;
  avatar_url?: string;
  /**
   * Rows in `contact_occurrences`, maintained by trigger (migration 042).
   * The source of truth for the warning triangle — the `Possui Ocorrência`
   * tag it used to read was never written by anything.
   */
  occurrence_count?: number;

  /* ---- Commercial relationship (migration 040) ----------------------
   * Everything above is identity; everything here is the relationship.
   * All optional: a contact created from an inbound WhatsApp message has
   * none of it, and most never will. */

  /** Day and month are what matter — the year is usually unknown. */
  birthday?: string | null;
  last_purchase_at?: string | null;
  /** When the customer said to come back. The automation clears it on use. */
  next_purchase_expected_at?: string | null;
  /** Typical gap between purchases. NULL means "unknown", not "zero" — the
   *  recompra automation skips those rather than inventing a cadence. */
  repurchase_cycle_days?: number | null;
  average_ticket?: number | null;
  /**
   * Catalogue products this customer buys or asked about (spec §11,
   * migration 054). Powers the `products` broadcast audience (§44).
   * Absent on a pre-054 database — every reader treats that as `[]`.
   */
  product_interest?: string[] | null;

  job_title?: string | null;
  /** CNPJ, or a CPF when the contact is a person. */
  tax_id?: string | null;
  city?: string | null;
  /** Two-letter UF, enforced by a CHECK. */
  state?: string | null;
  /** How they reached us. Free text. */
  source?: string | null;

  /** The customer asked us to stop. Broadcasts and automations must exclude
   *  these — it is a legal position, not a preference. */
  opted_out?: boolean;
  opted_out_at?: string | null;

  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  /**
   * `| null` and not just optional: the column is nullable, PostgREST
   * returns an explicit `null` for an unowned thread, and "give this back
   * to the pool" is a write of `null` rather than an omission. Typed as
   * `?: string` alone, that write did not compile.
   */
  assigned_agent_id?: string | null;
  last_message_text?: string;
  /**
   * `content_type` of the newest message (migration 047). Lets a row show
   * that a photo arrived even when it carried a caption — the case parsing
   * `last_message_text` cannot see.
   */
  last_message_kind?: string | null;
  /** `media_url` of the newest message, for the row's thumbnail (047). */
  last_message_media_url?: string | null;
  last_message_at?: string;
  /**
   * Who wrote the last message, and whether it arrived — migration 056.
   *
   * The WhatsApp model for a list row: what went OUT carries ticks and a
   * name, what came IN carries neither. `sender_type` is the direction
   * (`customer` = inbound) and still separates a colleague from the
   * assistant; `sender_id` is null for a customer, for the bot, and for
   * everything written before 056.
   *
   * All three are `undefined` on a database without the migration, which
   * is why the row degrades to plain text rather than to an error.
   */
  last_message_sender_type?: 'customer' | 'agent' | 'bot' | null;
  last_message_sender_id?: string | null;
  last_message_status?: Message['status'] | null;
  unread_count: number;
  /** When it entered `pending`. Null in every other status (migration 045). */
  waiting_since?: string | null;
  /**
   * Hidden from the inbox lists — not deleted (migration 045). Cleared
   * automatically when the customer writes again, which is what makes
   * hiding the safe answer to "get this out of my way".
   */
  hidden_at?: string | null;
  hidden_by?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * The open deal on this thread, if there is one.
   *
   * Populated by CONVERSATION_SELECT's embed of `deals` (FK
   * `deals.conversation_id`) and flattened by `normalizeConversation`. It is
   * what lets a conversation row show which stage the negotiation is in —
   * the single most useful thing to know while scanning a shared inbox,
   * because it tells you what the last message is probably about.
   *
   * One conversation can carry several deals over time; the flattening keeps
   * the most recent OPEN one, since a won or lost deal says nothing about
   * what the customer is writing about today.
   */
  deal?: ConversationDeal | null;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

/**
 * `new_message` arrives with migration 046 — until then the only rows in
 * the table are assignments (027). See that migration for why a customer
 * writing never produced a notification at all.
 */
export type NotificationType = 'conversation_assigned' | 'new_message';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  /**
   * The five nullable columns are `| null`, not merely optional.
   *
   * `?: string` says "the key may be absent". PostgREST never omits a
   * column — it sends `"conversation_id": null` — and the writer inserts
   * explicit nulls, so the type described a shape the data never takes.
   * Every `if (n.conversation_id)` happened to work anyway, which is why
   * it went unnoticed; anything reaching for `?? fallback` on one of these
   * did not.
   */
  conversation_id?: string | null;
  contact_id?: string | null;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string | null;
  title: string | null;
  body?: string | null;
  read_at?: string | null;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus =
  'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  /**
   * MIME type of `media_url`'s content, as Meta reported it. Inbound
   * media only — outbound URLs already carry a filename and extension.
   * Null on every row written before migration 039.
   */
  media_type?: string | null;
  /**
   * What the attachment says, in words — the spoken text of a voice
   * note, or a description of a photo (migration 049). Written by the
   * inbound webhook when the account has AI on and media understanding
   * enabled; null everywhere else, including on every row that predates
   * the migration.
   */
  media_transcript?: string | null;
  /** none | done | failed | unsupported — see migration 049. */
  media_transcript_status?: 'none' | 'done' | 'failed' | 'unsupported' | null;
  media_transcript_at?: string | null;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * The quick reply the agent used to write this message, when they did
   * (migration 065). What lets `/aberto` be an automation trigger.
   */
  quick_reply_id?: string | null;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
  /**
   * When true (the default), the inbound webhook copies received media
   * into the `chat-media` bucket so attachments outlive Meta's ~30-day
   * retention. Turning it off keeps storage flat and accepts that
   * inbound attachments expire. Migration 039.
   */
  mirror_inbound_media?: boolean;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

/** The slice of a deal a conversation row needs. */
export interface ConversationDeal {
  id: string;
  status: DealStatus;
  stage_id: string;
  pipeline_id: string;
  /**
   * The funnel's name rides along with the stage's. "Em andamento" exists in
   * both of PlastfortSul's pipelines, so the stage alone does not say where
   * a deal is — and the thread header states both.
   */
  stage?: {
    id: string;
    name: string;
    color: string;
    pipeline?: { name: string } | null;
  } | null;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
  /**
   * Joined, not stored. Present when the query asks for it — the contact
   * record does, because "Em andamento" exists in both funnels and the stage
   * name alone does not say which one the deal is in.
   */
  pipeline?: Pick<Pipeline, 'name'>;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  /**
   * Why it was lost — one of the keys in `@/lib/deals/outcome`, never the
   * translated label. Migration 043; until that runs the reason is appended
   * to `notes` instead and this stays undefined.
   */
  lost_reason?: string | null;
  lost_note?: string | null;
  /**
   * When the deal entered the stage it is in, maintained by trigger
   * (migration 065). The clock behind "24 h in Em Aberto". Absent on a
   * pre-065 database.
   */
  stage_entered_at?: string | null;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

/**
 * One stage change of a deal, including its creation — migration 065.
 *
 * Written by a database trigger on `deals`, never by the app, so every
 * surface that moves a deal produces one. `dispatched_at` is the outbox
 * marker the cron uses to fire `deal_stage_entered` exactly once.
 */
export interface DealStageEvent {
  id: string;
  account_id: string;
  deal_id: string;
  from_stage_id: string | null;
  to_stage_id: string;
  /** NULL when the write came from the engine or the service role. */
  changed_by: string | null;
  changed_at: string;
  dispatched_at: string | null;
}

/**
 * One line of a stage's playbook — see migration 041.
 *
 * Steps hang off the STAGE, not the deal: the work is a property of where a
 * deal has got to, so a deal picks its list up by arriving and drops it by
 * moving on. Nothing is copied per deal.
 */
export interface PlaybookStep {
  id: string;
  account_id: string;
  stage_id: string;
  position: number;
  title: string;
  /** Optional one-liner under the title — the "how", not a restatement. */
  hint?: string | null;
  created_at: string;
  updated_at?: string;
}

/**
 * A ticked step. A row exists iff the step is done; there is no `false`.
 */
export interface DealPlaybookProgress {
  deal_id: string;
  step_id: string;
  account_id: string;
  done_at: string;
  done_by?: string | null;
}

export type BroadcastStatus =
  'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus =
  'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /**
   * Set while a server-side delivery pass is fanning out, NULL when
   * idle. Claimed with a conditional UPDATE so two resumes can't both
   * send. Added in migration 038.
   */
  delivery_locked_at?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  /**
   * Positional body values for this recipient's template send
   * ({{1}}, {{2}}, …), frozen when the broadcast was planned so a
   * server-side resume reproduces the original pass exactly.
   * Added in migration 038; null on rows created before it.
   */
  template_params?: string[] | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply'
  /**
   * Something outside the product POSTed to `/api/hooks/<token>` —
   * Typebot, n8n, a landing page, a form.
   *
   * The payload arrives as `{{vars.*}}`, so an automation can write a
   * gclid into a custom field, tag the contact, open a deal. What it can
   * do is bounded by the hook's scopes, enforced in the engine.
   */
  | 'webhook_received'
  /**
   * A deal entered a stage — moved there, or created there. Recorded by
   * the database trigger of migration 065 and drained by the cron, so
   * every surface that moves a deal fires it (see
   * `@/lib/automations/stage-events`).
   */
  | 'deal_stage_entered'
  /**
   * A person on the team sent a message from the inbox. Filters on the
   * quick reply used (`/aberto`) or the template sent. Engine, flow and
   * assistant sends never fire it.
   */
  | 'team_message_sent'
  /**
   * A date on the contact record is today — the birthday, most of all.
   * Swept once a day by the cron; idempotent per contact and day through
   * `automation_logs.trigger_key`.
   */
  | 'date_field_reached';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation'
  /** Move the run's deal to a stage (migration 065). */
  | 'move_deal_stage'
  /** Write one field of the run's deal. */
  | 'update_deal'
  /** Cancel pending waits of other automations for this deal or contact. */
  | 'cancel_automations'
  /** Stop the run here, inside a branch too, with a reason for the log. */
  | 'end';

/**
 * `cancelled` and `skipped` arrived with migration 065: a run whose wait
 * was cancelled (the customer replied, the deal moved on), and a run the
 * reentry policy refused to start. Neither is a failure.
 */
export type AutomationLogStatus =
  'success' | 'partial' | 'failed' | 'cancelled' | 'skipped';

/** When an automation may start again for the same deal (or contact). */
export type AutomationReentryPolicy =
  'always' | 'never' | 'after_complete' | 'after_days';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  /**
   * `contains` (the default) is a raw substring test, so a short keyword
   * matches inside longer words — "k" fires on "thanks". `word` is the
   * boundary-aware alternative added for issue #409; see
   * `matchesWholeWord` in `@/lib/automations/engine` for its exact
   * semantics. Flows carry their own keyword config and stay
   * substring-only (`@/lib/flows/types`).
   */
  match_type: 'exact' | 'contains' | 'word';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export interface DealStageEnteredTriggerConfig {
  /** Redundant with the stage — kept so the builder can filter stages. */
  pipeline_id?: string;
  stage_id: string;
}

export interface TeamMessageSentTriggerConfig {
  /** The quick reply that was used — `/aberto`, by id. */
  quick_reply_id?: string;
  /** Or the Meta template that was sent, by name. Either one matches. */
  template_name?: string;
}

/** Contact date columns the sweep knows how to read. */
export type DateTriggerField =
  'birthday' | 'next_purchase_expected_at' | 'last_purchase_at';

export interface DateFieldReachedTriggerConfig {
  field: DateTriggerField;
  /** `HH:mm` — not before this local time. Defaults to 09:00. */
  at?: string;
  /** IANA zone the day and time are read in. Defaults to America/Sao_Paulo. */
  timezone?: string;
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | DealStageEnteredTriggerConfig
  | TeamMessageSentTriggerConfig
  | DateFieldReachedTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
  /**
   * `duration` (the default, and what every pre-065 step is) waits
   * `amount` × `unit`. `until_contact_date` sleeps until the date in a
   * contact column — Compra Futura — and re-reads it on waking, so a
   * date moved from the agenda moves the wait with it.
   */
  mode?: 'duration' | 'until_contact_date';
  /** With `until_contact_date`: which column. */
  field?: DateTriggerField;
  /** With `until_contact_date`: `HH:mm` local time to wake. Default 09:00. */
  at?: string;
  timezone?: string;
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day'
  /** The run's deal is in one of `stage_ids` (migration 065). */
  | 'deal_in_stage'
  /** The run's deal has `status = 'open'`. */
  | 'deal_is_open'
  /**
   * The customer wrote since the deal entered its stage (`operand:
   * 'stage_entry'`) or since this run started (`'run_start'`).
   */
  | 'customer_replied_since';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
  /** For `deal_in_stage`. `operand` as a comma-separated list also works. */
  stage_ids?: string[];
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export interface MoveDealStageStepConfig {
  stage_id: string;
  /**
   * Required when the target stage is a lost stage — the same gate the
   * board enforces (`@/lib/deals/outcome`). A key, never a label.
   */
  lost_reason?: string;
}

export interface UpdateDealStepConfig {
  field: 'title' | 'value' | 'expected_close_date' | 'notes';
  /** `notes` appends a line rather than replacing. Interpolates `{{vars.*}}`. */
  value: string;
}

export interface CancelAutomationsStepConfig {
  /** Whose pending waits: this run's deal, or everything of the contact. */
  scope: 'deal' | 'contact';
  /** Only these automations; empty or absent means every other automation. */
  automation_ids?: string[];
}

export interface EndStepConfig {
  /** Free text for `automation_logs.end_reason`. */
  reason?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | MoveDealStageStepConfig
  | UpdateDealStepConfig
  | CancelAutomationsStepConfig
  | EndStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;

  /* ---- Deal scope and cancellation rules (migration 065) --------------
   * All optional: absent on a pre-065 database, and every default keeps
   * an automation behaving exactly as it did before the migration. */

  /**
   * The funnel whose deals this automation works. A contact-level trigger
   * resolves the contact's newest open deal in this pipeline; NULL resolves
   * in any pipeline.
   */
  pipeline_id?: string | null;
  /** The inbound webhook cancels this automation's pending waits for the
   *  contact who replied, before any trigger fires. */
  cancel_on_reply?: boolean;
  /** Entering any of these stages cancels this automation's pending waits
   *  for that deal — the §22 list of the official flow, per automation. */
  cancel_when_stage_in?: string[];
  reentry_policy?: AutomationReentryPolicy;
  /** With `after_days`: how many. */
  reentry_days?: number | null;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  /** The deal this run worked, when it had one (migration 065). */
  deal_id?: string | null;
  /**
   * Why the run ended when it was not the end of the list —
   * `customer_replied`, `stage_entered:<id>`, `cancelled_by:<id>`,
   * `reentry_blocked`, `already_running`, `date_cleared`, `end_step`, or
   * the free text of an End step.
   */
  end_reason?: string | null;
  /** Idempotency key of a date sweep — `contact:<id>:<YYYY-MM-DD>`. */
  trigger_key?: string | null;
  created_at: string;
  contact?: Contact;
  deal?: Pick<Deal, 'id' | 'title'> | null;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

/** `media` arrived with migration 044 — a file with an optional caption. */
export type QuickReplyKind = 'text' | 'interactive' | 'media';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /**
   * What you type after the slash, WITHOUT it: `orcamento`, not
   * `/orcamento`. Lower-case and unique per account (migration 044).
   *
   * Distinct from the title on purpose. The `/` panel can already find
   * "Prazo de entrega" from `/pra` by word prefix, and that is not the same
   * thing: a shortcut is a short name somebody decides once and then types
   * without reading, and it survives the title being reworded.
   */
  shortcut?: string | null;
  /** Set when `kind === 'text'` or `'media'` (the caption). */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  /** Public chat-media URL. Set when `kind === 'media'` (migration 044). */
  media_url?: string | null;
  media_type?: string | null;
  created_at: string;
  updated_at: string;
}
