import type { Metadata, Viewport } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Geist_Mono, Inter } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
import { ThemeProvider } from '@/hooks/use-theme';
import { ThemedToaster } from '@/components/themed-toaster';
import {
  DEFAULT_MODE,
  DEFAULT_THEME,
  MODE_STORAGE_KEY,
  MODE_THEME_COLOR,
  MODES,
  NAV_STORAGE_KEY,
  STORAGE_KEY,
  THEME_IDS,
} from '@/lib/themes';

/**
 * The app's one text face.
 *
 * `adjustFontFallback` is OFF, and that is the whole point of this
 * block. Left on, Next synthesises a stand-in face — literally
 * `local("Arial")` with `size-adjust: 107.12%` — and puts it FIRST in
 * the stack, ahead of anything passed as `fallback`. So every load
 * before the woff2 lands paints the entire product in Arial stretched
 * 7% wider than it was drawn: letterforms nobody designed, at a width
 * nobody chose. It buys zero layout shift and pays for it in a typeface
 * that reads as broken — which is exactly the complaint that started
 * this ("a fonte tá estranha" on the sign-in screen, which is the first
 * screen anyone sees and the one most likely to be hit cold).
 *
 * With it off, the stack degrades to real faces: Segoe UI Variable on
 * Windows 11 (where this CRM is used all day), the platform UI face
 * elsewhere. Those are close enough to Inter's proportions that the
 * swap is a settle, not a jolt — and the frames before it are a
 * legitimate typeface rather than a distorted one.
 *
 * The shift that buys back is small and bounded: the file is preloaded
 * (`preload` defaults true and only the `latin` subset is cut), so on
 * anything but a cold cache the fallback is never painted at all.
 */
const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
  fallback: [
    'Segoe UI Variable Text',
    'Segoe UI',
    'system-ui',
    '-apple-system',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'sans-serif',
  ],
});

/**
 * The second family, and the only one — everything else in the app is
 * Inter.
 *
 * It exists for the places where a character has to line up under the
 * character above it: API keys, the `{{1}}` variables in a template,
 * phone numbers in the contacts table, run timestamps, raw JSON in the
 * automation builder. Those 26 call sites already asked for `font-mono`
 * and were silently rendering in Inter — the theme pointed `--font-mono`
 * at `--font-geist-mono`, a variable nothing ever defined.
 *
 * `fallback` is a real monospace stack rather than the automatic
 * metric-matched one. Next's default fallback is derived from Arial, so
 * a slow network would render a column of API keys in a PROPORTIONAL
 * face — the exact failure this font is here to prevent. Turning
 * `adjustFontFallback` off costs a hair of layout shift when the woff2
 * lands and buys a correct character grid from the first frame.
 */
const geistMono = Geist_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
  adjustFontFallback: false,
  // Not preloaded, and Inter is why. `preload` defaults to true, so
  // every route in the app — login included — shipped a
  // `<link rel=preload as=font>` for a face that appears on maybe six
  // screens, none of them above the fold, competing for the first-paint
  // connection with the ONE font every screen needs. The fallback here
  // is a real monospace stack (see above), so the pages that do use it
  // stay on a correct character grid while the woff2 arrives.
  preload: false,
});

export const metadata: Metadata = {
  title: {
    default: 'PlastfortSul',
    template: '%s — PlastfortSul',
  },
  description:
    'CRM comercial da PlastfortSul, operado sobre o WhatsApp Business.',
  robots: {
    index: false,
    follow: false,
  },
  /**
   * DECLARING `icons` TURNS THE FILE CONVENTIONS OFF, and that is worth
   * writing down because it cost a debugging round here.
   *
   * `src/app/apple-icon.png` exists and Next serves it — `/apple-icon.png`
   * returns 200 image/png. But no `<link rel="apple-touch-icon">` reached
   * the head, because this object was already present: an explicit
   * `icons` REPLACES what the `icon` / `apple-icon` file conventions
   * would have contributed rather than merging with it. The `icon` entry
   * below is why nobody noticed — it was declared, so it worked, and the
   * convention never had to.
   *
   * So both are listed. `/icon` is the 32px mark generated by
   * `icon.tsx`; `/apple-icon.png` is the 180px raster written by
   * `scripts/generate-app-icons.mjs`, and it is the ONLY icon an iPhone
   * reads when somebody adds this to their home screen.
   */
  icons: {
    icon: [{ url: '/icon' }],
    apple: [{ url: '/apple-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  /**
   * The iPhone half of "install this".
   *
   * `capable` makes Next emit `<meta name="mobile-web-app-capable">` —
   * the modern, standardised name, which is what Chrome reads. iOS also
   * still reads the ORIGINAL `apple-` prefixed spelling, and this
   * version of Next does not emit it (checked: `metadata.js` pushes only
   * the unprefixed tag). Modern iOS gets standalone from the manifest's
   * `display` instead, so the prefixed tag below is for the iPhones
   * still on 16.3 and earlier — see `other`.
   *
   * `title` is what appears UNDER the icon on the home screen. Without
   * it iOS uses the <title>, which is templated per route — so an app
   * added from the contacts page would sit on the home screen labelled
   * "Contatos — PlastfortSul", forever, because iOS reads it once.
   *
   * `statusBarStyle: 'default'` and deliberately not
   * `'black-translucent'`. Translucent means the web view extends UNDER
   * the clock and the battery, and every one of them then has to be
   * cleared with `env(safe-area-inset-top)` — which this app now honours
   * in the header, but the payoff (a few pixels of colour behind the
   * status bar) is not worth a whole class of "the bell is under the
   * clock" bugs on a surface nobody here can test daily.
   */
  appleWebApp: {
    capable: true,
    title: 'PlastfortSul',
    statusBarStyle: 'default',
  },
  other: {
    // The legacy spelling, for iOS 16.3 and older. Harmless everywhere
    // else — a browser that does not know it ignores it.
    'apple-mobile-web-app-capable': 'yes',
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export const viewport: Viewport = {
  /**
   * NO `themeColor` HERE, AND THAT IS THE FIX.
   *
   * It used to be two entries keyed on `prefers-color-scheme` — the
   * OPERATING SYSTEM's light/dark. This app's mode is not the system's:
   * it is `data-mode`, read from localStorage, defaulting to LIGHT, and
   * the picker offers no "follow the system" at all. So the ordinary
   * case — a phone set to dark, the app in its default light — painted
   * the browser's status bar `#0f1115` above a white interface.
   *
   * A `<meta>` cannot express "follow this DOM attribute", so the tag
   * is written imperatively instead: the boot script below stamps it in
   * the same breath as `data-mode`, before first paint, and
   * `use-theme.tsx` rewrites it whenever the mode changes. Declaring it
   * here as well would leave TWO `theme-color` tags in the head, and
   * the browser honours the first one it finds — which would be Next's
   * static one, i.e. the bug again.
   *
   * See `MODE_THEME_COLOR` in `lib/themes.ts` for the values.
   */
  colorScheme: 'light dark',
  /**
   * THE ANDROID KEYBOARD.
   *
   * The default (`resizes-visual`) leaves the layout viewport at its
   * full height and slides the keyboard OVER it — so the composer this
   * app is built around ends up underneath the keyboard the user opened
   * to type into it. The note in `globals.css` about `dvh` describes the
   * same failure from the other side: `vh` does not move when the
   * keyboard opens, and neither does the layout.
   *
   * `resizes-content` makes the layout viewport itself shrink, which is
   * what every `dvh` and every `flex-1` in the shell is already written
   * against — the thread scrolls, the composer stays on screen.
   */
  interactiveWidget: 'resizes-content',
};

// Inline boot script — runs before React hydrates so the user's
// chosen accent (data-theme) AND mode (data-mode) are on the <html>
// element before first paint. Without this every page load flashes
// the server-rendered defaults for a frame before the React tree
// mounts and applies the picked values.
//
// Kept dependency-free (no imports, no JSX) — must be a string the
// browser can run as a single <script>. Knowledge of valid ids is
// sourced from the THEME_IDS / MODES constants so adding one doesn't
// silently break the boot path.
/**
 * The signature.
 *
 * Every studio leaves one somewhere. This one is in the console and in a
 * `data-` attribute on <html>, which means it costs nothing to render, cannot
 * shift a pixel, and is found only by someone who opened DevTools — which is
 * exactly the audience it is for.
 *
 * `beforeInteractive` alongside the theme boot so it is the first thing in the
 * log rather than the last, buried under a page of Fast Refresh notices.
 */
const SIGNATURE_SCRIPT = `
(function(){
  try {
    var line = 'a CL passou por aqui';
    document.documentElement.dataset.cl = line;
    console.log(
      '%c ' + line + ' ',
      'background:#2f63c9;color:#fff;padding:6px 12px;border-radius:6px;font-weight:600;letter-spacing:.02em'
    );
    console.log('%ccreativelane.io', 'color:#8a94a6;font-size:11px');
  } catch (_e) {}
})();
`;

/**
 * Catch Chrome's install offer before anything can miss it.
 *
 * `beforeinstallprompt` fires ONCE per page load, as soon as the browser
 * has read the manifest and decided the app qualifies — which is long
 * before React hydrates, and very long before somebody navigates to
 * Configurações → Aparência where the install card lives. A listener
 * registered from a component's effect is a listener that has already
 * missed it, every time, and the card would simply never appear.
 *
 * So the event is caught here, at the top of the document, and parked on
 * `window`. `preventDefault()` is what suppresses Chrome's own
 * mini-infobar — without it the browser makes the offer in its way and
 * the app never gets to make it in ours.
 *
 * The custom event is how the React side finds out, since assigning to a
 * property notifies nobody. See `install-app-card.tsx`.
 *
 * Inline and dependency-free for the same reason as the theme boot: it
 * has to run before the framework does.
 */
const INSTALL_PROMPT_SCRIPT = `
(function(){
  try {
    window.__pwaInstallPrompt = null;
    var notify = function () {
      window.dispatchEvent(new Event('pwa:installability'));
    };
    window.addEventListener('beforeinstallprompt', function (e) {
      e.preventDefault();
      window.__pwaInstallPrompt = e;
      notify();
    });
    window.addEventListener('appinstalled', function () {
      window.__pwaInstallPrompt = null;
      notify();
    });
  } catch (_e) {}
})();
`;

const THEME_BOOT_SCRIPT = `
(function(){
  var d = document.documentElement;
  try {
    var THEME_KEY = ${JSON.stringify(STORAGE_KEY)};
    var THEME_DEFAULT = ${JSON.stringify(DEFAULT_THEME)};
    var THEMES = ${JSON.stringify(THEME_IDS)};
    var savedTheme = localStorage.getItem(THEME_KEY);
    d.dataset.theme = THEMES.indexOf(savedTheme) !== -1 ? savedTheme : THEME_DEFAULT;

    var MODE_KEY = ${JSON.stringify(MODE_STORAGE_KEY)};
    var MODE_DEFAULT = ${JSON.stringify(DEFAULT_MODE)};
    var MODES = ${JSON.stringify(MODES)};
    var savedMode = localStorage.getItem(MODE_KEY);
    d.dataset.mode = MODES.indexOf(savedMode) !== -1 ? savedMode : MODE_DEFAULT;

    // The browser's own chrome, in the app's mode rather than the
    // system's. Created here rather than declared in \`viewport\` so
    // there is exactly one such tag and it can follow \`data-mode\`;
    // \`use-theme.tsx\` keeps it in step from here on.
    var THEME_COLORS = ${JSON.stringify(MODE_THEME_COLOR)};
    var meta = document.querySelector('meta[name="theme-color"]');
    if (!meta) {
      meta = document.createElement('meta');
      meta.setAttribute('name', 'theme-color');
      document.head.appendChild(meta);
    }
    meta.setAttribute('content', THEME_COLORS[d.dataset.mode] || THEME_COLORS[MODE_DEFAULT]);

    // Sidebar collapse. Same reasoning as theme: stamping the
    // attribute here is what keeps the menu from snapping shut on
    // every navigation for someone who collapsed it.
    d.dataset.nav =
      localStorage.getItem(${JSON.stringify(NAV_STORAGE_KEY)}) === 'collapsed'
        ? 'collapsed'
        : 'expanded';
  } catch (_e) {
    d.dataset.theme = ${JSON.stringify(DEFAULT_THEME)};
    d.dataset.mode = ${JSON.stringify(DEFAULT_MODE)};
    d.dataset.nav = 'expanded';
  }
})();
`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      data-theme={DEFAULT_THEME}
      data-mode={DEFAULT_MODE}
      data-nav="expanded"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
      // The `theme-boot` script below rewrites `data-theme` and
      // `data-mode` on <html> from localStorage before React hydrates,
      // so for any non-default choice the client DOM intentionally
      // differs from the server-rendered defaults. suppressHydration-
      // Warning silences the expected mismatch — it only applies to
      // this element's own attributes, so genuine mismatches in
      // children still surface.
      suppressHydrationWarning
    >
      <head>
        <Script
          id="theme-boot"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: THEME_BOOT_SCRIPT }}
        />
        <Script
          id="install-prompt"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: INSTALL_PROMPT_SCRIPT }}
        />
        <Script
          id="cl"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: SIGNATURE_SCRIPT }}
        />
      </head>
      <body className="bg-background text-foreground min-h-full font-sans">
        <NextIntlClientProvider messages={messages} locale={locale}>
          <ThemeProvider>
            {children}
            <ThemedToaster />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
